name: Create zip archive on tag

on:
  push:
    branches: [main, 5.7.x, 5.6.x, 5.7.x-pm, 5.6.x-pm, 5.7.x-staging]    
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1.0.0
      
      - name: Create zip archive
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          zip -r temp.zip .
          mkdir IvyPaymentPlugin
          unzip temp.zip -d IvyPaymentPlugin
          rm temp.zip
          zip -r IvySW5-${BRANCH_NAME}.zip IvyPaymentPlugin

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: IvyPaymentPlugin
          path: IvyPaymentPlugin

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: IvySW5-*.zip
